// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class CategorySpec
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string InputType { get; set; }

    public bool IsRequired { get; set; }

    public int SortOrder { get; set; }

    public bool IsActive { get; set; }

    public bool AllowCustomInput { get; set; }

    public virtual ICollection<CategorySpecMapping> CategorySpecMappings { get; set; } = new List<CategorySpecMapping>();

    public virtual ICollection<CategorySpecOption> CategorySpecOptions { get; set; } = new List<CategorySpecOption>();
}