// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class CategoryAttribute
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string InputType { get; set; }

    public bool IsRequired { get; set; }

    public bool IsActive { get; set; }

    public bool AllowCustomInput { get; set; }

    public virtual ICollection<CategoryAttributeMapping> CategoryAttributeMappings { get; set; } = new List<CategoryAttributeMapping>();

    public virtual ICollection<CategoryAttributeOption> CategoryAttributeOptions { get; set; } = new List<CategoryAttributeOption>();
}