// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class CategorySpecMapping
{
    public int CategoryId { get; set; }

    public int CategorySpecId { get; set; }

    public bool IsFilterable { get; set; }

    public int Sort { get; set; }

    public virtual Category Category { get; set; }

    public virtual CategorySpec CategorySpec { get; set; }
}