// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class Coupon
{
    public int Id { get; set; }

    public int StoreId { get; set; }

    public int SellerId { get; set; }

    public string CouponCode { get; set; }

    public string Title { get; set; }

    public byte DistributionType { get; set; }

    public byte CouponType { get; set; }

    public decimal DiscountValue { get; set; }

    public decimal MinimumSpend { get; set; }

    public decimal? MaximumDiscount { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public int TotalQuantity { get; set; }

    public int UsedQuantity { get; set; }

    public int PerUserLimit { get; set; }

    public bool ApplyToAll { get; set; }

    public bool IsExclusive { get; set; }

    public byte Status { get; set; }

    public bool IsDeleted { get; set; }

    public byte[] RowVersion { get; set; }

    public int UpdatedBy { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<MemberCoupon> MemberCoupons { get; set; } = new List<MemberCoupon>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual User Seller { get; set; }

    public virtual Store Store { get; set; }

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}