// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ISpanShop.Models.EFModels;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class ISpanShopDBContext : DbContext
{
	public ISpanShopDBContext(DbContextOptions<ISpanShopDBContext> options)
		: base(options)
	{
	}

	public virtual DbSet<Address> Addresses { get; set; }

	public virtual DbSet<BlacklistRecord> BlacklistRecords { get; set; }

	public virtual DbSet<Brand> Brands { get; set; }

	public virtual DbSet<Cart> Carts { get; set; }

	public virtual DbSet<CartItem> CartItems { get; set; }

	public virtual DbSet<Category> Categories { get; set; }

	public virtual DbSet<ChatMessage> ChatMessages { get; set; }

	public virtual DbSet<LoginHistory> LoginHistories { get; set; }

	public virtual DbSet<MemberProfile> MemberProfiles { get; set; }

	public virtual DbSet<MembershipLevel> MembershipLevels { get; set; }

	public virtual DbSet<Order> Orders { get; set; }

	public virtual DbSet<OrderDetail> OrderDetails { get; set; }

	public virtual DbSet<OrderReview> OrderReviews { get; set; }

	public virtual DbSet<PaymentLog> PaymentLogs { get; set; }

	public virtual DbSet<PointHistory> PointHistories { get; set; }

	public virtual DbSet<Product> Products { get; set; }

	public virtual DbSet<ProductImage> ProductImages { get; set; }

	public virtual DbSet<ProductVariant> ProductVariants { get; set; }

	public virtual DbSet<ReviewImage> ReviewImages { get; set; }

	public virtual DbSet<Role> Roles { get; set; }

	public virtual DbSet<SensitiveWord> SensitiveWords { get; set; }

	public virtual DbSet<SensitiveWordCategory> SensitiveWordCategories { get; set; }

	public virtual DbSet<Store> Stores { get; set; }

	public virtual DbSet<SupportTicket> SupportTickets { get; set; }

	public virtual DbSet<User> Users { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Address>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__Addresse__3214EC0774CFB27B");

			entity.Property(e => e.City).HasMaxLength(20);
			entity.Property(e => e.IsDefault).HasDefaultValue(false);
			entity.Property(e => e.RecipientName).HasMaxLength(50);
			entity.Property(e => e.RecipientPhone)
				.HasMaxLength(20)
				.IsUnicode(false);
			entity.Property(e => e.Region).HasMaxLength(20);
			entity.Property(e => e.Street).HasMaxLength(200);

			entity.HasOne(d => d.User).WithMany(p => p.Addresses)
				.HasForeignKey(d => d.UserId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_Addresses_Users");
		});

		modelBuilder.Entity<BlacklistRecord>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__Blacklis__3214EC07D24B6B8B");

			entity.Property(e => e.CreatedAt)
				.HasDefaultValueSql("(getdate())")
				.HasColumnType("datetime");
			entity.Property(e => e.Reason).HasMaxLength(200);
			entity.Property(e => e.UnblockAt).HasColumnType("datetime");

			entity.HasOne(d => d.AdminUser).WithMany(p => p.BlacklistRecordAdminUsers)
				.HasForeignKey(d => d.AdminUserId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_BlacklistRecords_AdminUser");

			entity.HasOne(d => d.BlockedUser).WithMany(p => p.BlacklistRecordBlockedUsers)
				.HasForeignKey(d => d.BlockedUserId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_BlacklistRecords_BlockedUser");
		});

		modelBuilder.Entity<Brand>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__Brands__3214EC072F43546C");

			entity.Property(e => e.IsDeleted).HasDefaultValue(false);
			entity.Property(e => e.IsVisible).HasDefaultValue(true);
			entity.Property(e => e.LogoUrl).HasMaxLength(500);
			entity.Property(e => e.Name)
				.IsRequired()
				.HasMaxLength(100);
			entity.Property(e => e.Sort).HasDefaultValue(0);
		});

		modelBuilder.Entity<Cart>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__Carts__3214EC07EF4196CB");

			entity.HasIndex(e => e.UserId, "UQ__Carts__1788CC4DE0447113").IsUnique();

			entity.HasOne(d => d.User).WithOne(p => p.Cart)
				.HasForeignKey<Cart>(d => d.UserId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_Carts_Users");
		});

		modelBuilder.Entity<CartItem>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__CartItem__3214EC07A3A2A184");

			entity.HasIndex(e => e.CartId, "IX_CartItems_CartId");

			entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

			entity.HasOne(d => d.Cart).WithMany(p => p.CartItems)
				.HasForeignKey(d => d.CartId)
				.HasConstraintName("FK_CartItems_Carts");

			entity.HasOne(d => d.Product).WithMany(p => p.CartItems)
				.HasForeignKey(d => d.ProductId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_CartItems_Products");

			entity.HasOne(d => d.Store).WithMany(p => p.CartItems)
				.HasForeignKey(d => d.StoreId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_CartItems_Stores");

			entity.HasOne(d => d.Variant).WithMany(p => p.CartItems)
				.HasForeignKey(d => d.VariantId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_CartItems_ProductVariants");
		});

		modelBuilder.Entity<Category>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__Categori__3214EC076D953744");

			entity.Property(e => e.IconUrl).HasMaxLength(500);
			entity.Property(e => e.IsVisible).HasDefaultValue(true);
			entity.Property(e => e.Name)
				.IsRequired()
				.HasMaxLength(50);
			entity.Property(e => e.Sort).HasDefaultValue(0);

			entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
				.HasForeignKey(d => d.ParentId)
				.HasConstraintName("FK_Categories_Parent");
		});

		modelBuilder.Entity<ChatMessage>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__ChatMess__3214EC07C31D67BE");

			entity.Property(e => e.IsRead).HasDefaultValue(false);
			entity.Property(e => e.SentAt)
				.HasDefaultValueSql("(getdate())")
				.HasColumnType("datetime");

			entity.HasOne(d => d.Receiver).WithMany(p => p.ChatMessageReceivers)
				.HasForeignKey(d => d.ReceiverId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_ChatMessages_Receiver");

			entity.HasOne(d => d.Sender).WithMany(p => p.ChatMessageSenders)
				.HasForeignKey(d => d.SenderId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_ChatMessages_Sender");
		});

		modelBuilder.Entity<LoginHistory>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__LoginHis__3214EC0782A1C77C");

			entity.ToTable("LoginHistory");

			entity.Property(e => e.Ipaddress)
				.HasMaxLength(50)
				.IsUnicode(false)
				.HasColumnName("IPAddress");
			entity.Property(e => e.LoginTime)
				.HasDefaultValueSql("(getdate())")
				.HasColumnType("datetime");

			entity.HasOne(d => d.User).WithMany(p => p.LoginHistories)
				.HasForeignKey(d => d.UserId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_LoginHistory_Users");
		});

		modelBuilder.Entity<MemberProfile>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__MemberPr__3214EC0723A7A576");

			entity.HasIndex(e => e.UserId, "UQ__MemberPr__1788CC4D7D386EA3").IsUnique();

			entity.Property(e => e.EmailNotification).HasDefaultValue(true);
			entity.Property(e => e.FullName).HasMaxLength(50);
			entity.Property(e => e.PhoneNumber)
				.HasMaxLength(20)
				.IsUnicode(false);
			entity.Property(e => e.PointBalance).HasDefaultValue(0);
			entity.Property(e => e.TotalSpending)
				.HasDefaultValue(0m)
				.HasColumnType("decimal(18, 2)");
			entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

			entity.HasOne(d => d.Level).WithMany(p => p.MemberProfiles)
				.HasForeignKey(d => d.LevelId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_MemberProfiles_MembershipLevels");

			entity.HasOne(d => d.User).WithOne(p => p.MemberProfile)
				.HasForeignKey<MemberProfile>(d => d.UserId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_MemberProfiles_Users");
		});

		modelBuilder.Entity<MembershipLevel>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__Membersh__3214EC074C4502A2");

			entity.Property(e => e.DiscountRate).HasColumnType("decimal(3, 2)");
			entity.Property(e => e.LevelName)
				.IsRequired()
				.HasMaxLength(20);
			entity.Property(e => e.MinSpending).HasColumnType("decimal(18, 2)");
		});

		modelBuilder.Entity<Order>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__Orders__3214EC07684C0E8D");

			entity.HasIndex(e => e.OrderNumber, "UQ__Orders__CAC5E7430C2EB5F8").IsUnique();

			entity.Property(e => e.CompletedAt).HasColumnType("datetime");
			entity.Property(e => e.CreatedAt)
				.HasDefaultValueSql("(getdate())")
				.HasColumnType("datetime");
			entity.Property(e => e.DiscountAmount)
				.HasDefaultValue(0m)
				.HasColumnType("decimal(18, 2)");
			entity.Property(e => e.FinalAmount).HasColumnType("decimal(18, 2)");
			entity.Property(e => e.Note).HasMaxLength(500);
			entity.Property(e => e.OrderNumber)
				.IsRequired()
				.HasMaxLength(30)
				.IsUnicode(false);
			entity.Property(e => e.PaymentDate).HasColumnType("datetime");
			entity.Property(e => e.PointDiscount).HasDefaultValue(0);
			entity.Property(e => e.RecipientAddress).HasMaxLength(300);
			entity.Property(e => e.RecipientName).HasMaxLength(50);
			entity.Property(e => e.RecipientPhone)
				.HasMaxLength(20)
				.IsUnicode(false);
			entity.Property(e => e.ShippingFee)
				.HasDefaultValue(0m)
				.HasColumnType("decimal(18, 2)");
			entity.Property(e => e.Status).HasDefaultValue((byte)0);
			entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");

			entity.HasOne(d => d.Store).WithMany(p => p.Orders)
				.HasForeignKey(d => d.StoreId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_Orders_Stores");

			entity.HasOne(d => d.User).WithMany(p => p.Orders)
				.HasForeignKey(d => d.UserId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_Orders_Users");
		});

		modelBuilder.Entity<OrderDetail>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__OrderDet__3214EC07093E04A0");

			entity.Property(e => e.CoverImage).HasMaxLength(500);
			entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
			entity.Property(e => e.ProductName).HasMaxLength(200);
			entity.Property(e => e.SkuCode).HasMaxLength(100);
			entity.Property(e => e.VariantName).HasMaxLength(100);

			entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
				.HasForeignKey(d => d.OrderId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_OrderDetails_Orders");

			entity.HasOne(d => d.Product).WithMany(p => p.OrderDetails)
				.HasForeignKey(d => d.ProductId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_OrderDetails_Products");

			entity.HasOne(d => d.Variant).WithMany(p => p.OrderDetails)
				.HasForeignKey(d => d.VariantId)
				.HasConstraintName("FK_OrderDetails_ProductVariants");
		});

		modelBuilder.Entity<OrderReview>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__OrderRev__3214EC07ED91B9B2");

			entity.Property(e => e.CreatedAt)
				.HasDefaultValueSql("(getdate())")
				.HasColumnType("datetime");
			entity.Property(e => e.IsHidden).HasDefaultValue(false);

			entity.HasOne(d => d.Order).WithMany(p => p.OrderReviews)
				.HasForeignKey(d => d.OrderId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_OrderReviews_Orders");

			entity.HasOne(d => d.User).WithMany(p => p.OrderReviews)
				.HasForeignKey(d => d.UserId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_OrderReviews_Users");
		});

		modelBuilder.Entity<PaymentLog>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__PaymentL__3214EC073CACB73B");

			entity.Property(e => e.CreatedAt)
				.HasDefaultValueSql("(getdate())")
				.HasColumnType("datetime");
			entity.Property(e => e.MerchantTradeNo)
				.HasMaxLength(20)
				.IsUnicode(false);
			entity.Property(e => e.PaymentDate).HasColumnType("datetime");
			entity.Property(e => e.PaymentType)
				.HasMaxLength(20)
				.IsUnicode(false);
			entity.Property(e => e.RtnMsg).HasMaxLength(200);
			entity.Property(e => e.TradeAmt).HasColumnType("decimal(18, 2)");
			entity.Property(e => e.TradeNo)
				.HasMaxLength(50)
				.IsUnicode(false);

			entity.HasOne(d => d.Order).WithMany(p => p.PaymentLogs)
				.HasForeignKey(d => d.OrderId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_PaymentLogs_Orders");
		});

		modelBuilder.Entity<PointHistory>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__PointHis__3214EC07C39463C8");

			entity.ToTable("PointHistory");

			entity.Property(e => e.CreatedAt)
				.HasDefaultValueSql("(getdate())")
				.HasColumnType("datetime");
			entity.Property(e => e.Description).HasMaxLength(200);
			entity.Property(e => e.OrderNumber)
				.HasMaxLength(50)
				.IsUnicode(false);

			entity.HasOne(d => d.User).WithMany(p => p.PointHistories)
				.HasForeignKey(d => d.UserId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_PointHistory_Users");
		});

		modelBuilder.Entity<Product>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__Products__3214EC07D0F04B79");

			entity.Property(e => e.CreatedAt)
				.HasDefaultValueSql("(getdate())")
				.HasColumnType("datetime");
			entity.Property(e => e.MaxPrice).HasColumnType("decimal(18, 2)");
			entity.Property(e => e.MinPrice).HasColumnType("decimal(18, 2)");
			entity.Property(e => e.Name)
				.IsRequired()
				.HasMaxLength(200);
			entity.Property(e => e.Status).HasDefaultValue((byte)1);
			entity.Property(e => e.TotalSales).HasDefaultValue(0);
			entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
			entity.Property(e => e.VideoUrl).HasMaxLength(500);
			entity.Property(e => e.ViewCount).HasDefaultValue(0);

			entity.HasOne(d => d.Brand).WithMany(p => p.Products)
				.HasForeignKey(d => d.BrandId)
				.HasConstraintName("FK_Products_Brands");

			entity.HasOne(d => d.Category).WithMany(p => p.Products)
				.HasForeignKey(d => d.CategoryId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_Products_Categories");

			entity.HasOne(d => d.Store).WithMany(p => p.Products)
				.HasForeignKey(d => d.StoreId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_Products_Stores");
		});

		modelBuilder.Entity<ProductImage>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__ProductI__3214EC07AB0C8D36");

			entity.Property(e => e.ImageUrl)
				.IsRequired()
				.HasMaxLength(500);
			entity.Property(e => e.IsMain).HasDefaultValue(false);
			entity.Property(e => e.SortOrder).HasDefaultValue(0);

			entity.HasOne(d => d.Product).WithMany(p => p.ProductImages)
				.HasForeignKey(d => d.ProductId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_ProductImages_Products");

			entity.HasOne(d => d.Variant).WithMany(p => p.ProductImages)
				.HasForeignKey(d => d.VariantId)
				.HasConstraintName("FK_ProductImages_ProductVariants");
		});

		modelBuilder.Entity<ProductVariant>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__ProductV__3214EC07DC49B123");

			entity.HasIndex(e => e.SkuCode, "UQ__ProductV__3B24394881412651").IsUnique();

			entity.Property(e => e.IsDeleted).HasDefaultValue(false);
			entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
			entity.Property(e => e.SafetyStock).HasDefaultValue(0);
			entity.Property(e => e.SkuCode).HasMaxLength(100);
			entity.Property(e => e.Stock).HasDefaultValue(0);
			entity.Property(e => e.VariantName).HasMaxLength(100);

			entity.HasOne(d => d.Product).WithMany(p => p.ProductVariants)
				.HasForeignKey(d => d.ProductId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_ProductVariants_Products");
		});

		modelBuilder.Entity<ReviewImage>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__ReviewIm__3214EC076391DFB4");

			entity.Property(e => e.ImageUrl)
				.IsRequired()
				.HasMaxLength(500);

			entity.HasOne(d => d.Review).WithMany(p => p.ReviewImages)
				.HasForeignKey(d => d.ReviewId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_ReviewImages_OrderReviews");
		});

		modelBuilder.Entity<Role>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC07D8343E1E");

			entity.Property(e => e.Description).HasMaxLength(200);
			entity.Property(e => e.RoleName)
				.IsRequired()
				.HasMaxLength(20);
		});

		modelBuilder.Entity<SensitiveWord>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__Sensitiv__3214EC071733DFD0");

			entity.Property(e => e.Category).HasMaxLength(50);
			entity.Property(e => e.CreatedTime)
				.HasDefaultValueSql("(getdate())")
				.HasColumnType("datetime");
			entity.Property(e => e.IsActive).HasDefaultValue(true);
			entity.Property(e => e.Word)
				.IsRequired()
				.HasMaxLength(100);

			// 建立與 SensitiveWordCategory 的外鍵關聯
			entity.HasOne(d => d.CategoryNavigation)
				.WithMany(p => p.SensitiveWords)
				.HasForeignKey(d => d.CategoryId)
				.HasConstraintName("FK_SensitiveWords_SensitiveWordCategories");
		});

		// 新增：敏感字分類表設定
		modelBuilder.Entity<SensitiveWordCategory>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK_SensitiveWordCategories");
			entity.ToTable("SensitiveWordCategories");
			entity.Property(e => e.Name).IsRequired().HasMaxLength(50);
		});

		modelBuilder.Entity<Store>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__Stores__3214EC076B8719C1");

			entity.Property(e => e.CreatedAt)
				.HasDefaultValueSql("(getdate())")
				.HasColumnType("datetime");
			entity.Property(e => e.IsVerified).HasDefaultValue(false);
			entity.Property(e => e.StoreName)
				.IsRequired()
				.HasMaxLength(50);

			entity.HasOne(d => d.User).WithMany(p => p.Stores)
				.HasForeignKey(d => d.UserId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_Stores_Users");
		});

		modelBuilder.Entity<SupportTicket>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__SupportT__3214EC078EBAD2A6");

			entity.Property(e => e.AttachmentUrl).HasMaxLength(500);
			entity.Property(e => e.CreatedAt)
				.HasDefaultValueSql("(getdate())")
				.HasColumnType("datetime");
			entity.Property(e => e.ResolvedAt).HasColumnType("datetime");
			entity.Property(e => e.Status).HasDefaultValue((byte)0);
			entity.Property(e => e.Subject).HasMaxLength(100);

			entity.HasOne(d => d.Order).WithMany(p => p.SupportTickets)
				.HasForeignKey(d => d.OrderId)
				.HasConstraintName("FK_SupportTickets_Orders");

			entity.HasOne(d => d.User).WithMany(p => p.SupportTickets)
				.HasForeignKey(d => d.UserId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_SupportTickets_Users");
		});

		modelBuilder.Entity<User>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__Users__3214EC079CC23F85");

			entity.HasIndex(e => e.Account, "UQ__Users__B0C3AC465067402A").IsUnique();

			entity.Property(e => e.Account)
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.ConfirmCode)
				.HasMaxLength(100)
				.IsUnicode(false);
			entity.Property(e => e.CreatedAt)
				.HasDefaultValueSql("(getdate())")
				.HasColumnType("datetime");
			entity.Property(e => e.Email)
				.IsRequired()
				.HasMaxLength(100);
			entity.Property(e => e.IsBlacklisted).HasDefaultValue(false);
			entity.Property(e => e.IsConfirmed).HasDefaultValue(false);
			entity.Property(e => e.IsSeller).HasDefaultValue(false);
			entity.Property(e => e.Password)
				.HasMaxLength(255)
				.IsUnicode(false);
			entity.Property(e => e.Provider)
				.HasMaxLength(20)
				.IsUnicode(false);
			entity.Property(e => e.ProviderId)
				.HasMaxLength(100)
				.IsUnicode(false);
			entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

			entity.HasOne(d => d.Role).WithMany(p => p.Users)
				.HasForeignKey(d => d.RoleId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_Users_Roles");
		});

		OnModelCreatingPartial(modelBuilder);
	}

	partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}