// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class LoginHistory
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string AttemptedAccount { get; set; }

    public string Ipaddress { get; set; }

    public DateTime LoginTime { get; set; }

    public bool IsSuccess { get; set; }

    public virtual User User { get; set; }
}