// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class MemberCoupon
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int CouponId { get; set; }

    public byte UsageStatus { get; set; }

    public long? OrderId { get; set; }

    public DateTime ReceivedAt { get; set; }

    public DateTime? UsedAt { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual Order Order { get; set; }

    public virtual User User { get; set; }
}