// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class ProductVariant
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public string SkuCode { get; set; }

    public string VariantName { get; set; }

    public string SpecValueJson { get; set; }

    public decimal Price { get; set; }

    public int? Stock { get; set; }

    public int? SafetyStock { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Product Product { get; set; }

    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();
}