// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class PromotionRule
{
    public int Id { get; set; }

    public int PromotionId { get; set; }

    public int RuleType { get; set; }

    public decimal Threshold { get; set; }

    public int DiscountType { get; set; }

    public decimal DiscountValue { get; set; }

    public virtual Promotion Promotion { get; set; }
}