// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class PromotionItem
{
    public int Id { get; set; }

    public int PromotionId { get; set; }

    public int ProductId { get; set; }

    public decimal OriginalPrice { get; set; }

    public decimal? DiscountPrice { get; set; }

    public int? DiscountPercent { get; set; }

    public int? QuantityLimit { get; set; }

    public int? StockLimit { get; set; }

    public int SoldCount { get; set; }

    public virtual Product Product { get; set; }

    public virtual Promotion Promotion { get; set; }
}