// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class ReturnRequest
{
    public long Id { get; set; }

    public long OrderId { get; set; }

    public string ReasonCategory { get; set; }

    public string ReasonDescription { get; set; }

    public decimal RefundAmount { get; set; }

    public byte Status { get; set; }

    public string AdminRemark { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<ReturnRequestImage> ReturnRequestImages { get; set; } = new List<ReturnRequestImage>();
}