// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class ReturnRequestImage
{
    public long Id { get; set; }

    public long ReturnRequestId { get; set; }

    public string ImageUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ReturnRequest ReturnRequest { get; set; }
}