// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ISpanShop.Models.EFModels;
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class SensitiveWord
{
    public int Id { get; set; }

    public string Word { get; set; }

    public string Category { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedTime { get; set; }

    public int? CategoryId { get; set; }

	// 這是導覽屬性，對應到剛才 Context 裡的 CategoryNavigation
	public virtual SensitiveWordCategory CategoryNavigation { get; set; }
}