// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class SupportTicket
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public long? OrderId { get; set; }

    public byte Category { get; set; }

    public string Subject { get; set; }

    public string Description { get; set; }

    public string AttachmentUrl { get; set; }

    public byte? Status { get; set; }

    public string AdminReply { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? ResolvedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual User User { get; set; }
}