// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class User
{
    public int Id { get; set; }

    public int RoleId { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string Provider { get; set; }

    public string ProviderId { get; set; }

    public bool? IsConfirmed { get; set; }

    public string ConfirmCode { get; set; }

    public bool? IsBlacklisted { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? IsSeller { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual ICollection<BlacklistRecord> BlacklistRecordAdminUsers { get; set; } = new List<BlacklistRecord>();

    public virtual ICollection<BlacklistRecord> BlacklistRecordBlockedUsers { get; set; } = new List<BlacklistRecord>();

    public virtual Cart Cart { get; set; }

    public virtual ICollection<ChatMessage> ChatMessageReceivers { get; set; } = new List<ChatMessage>();

    public virtual ICollection<ChatMessage> ChatMessageSenders { get; set; } = new List<ChatMessage>();

    public virtual ICollection<LoginHistory> LoginHistories { get; set; } = new List<LoginHistory>();

    public virtual MemberProfile MemberProfile { get; set; }

    public virtual ICollection<OrderReview> OrderReviews { get; set; } = new List<OrderReview>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PointHistory> PointHistories { get; set; } = new List<PointHistory>();

    public virtual Role Role { get; set; }

    public virtual ICollection<Store> Stores { get; set; } = new List<Store>();

    public virtual ICollection<SupportTicket> SupportTickets { get; set; } = new List<SupportTicket>();
}