// <auto-generated />
using System;
using ISpanShop.Models.EfModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISpanShop.Models.Migrations
{
    [DbContext(typeof(ISpanShopDBContext))]
    [Migration("20260419121341_AddUserIdToPasswordResetToken")]
    partial class AddUserIdToPasswordResetToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdminLevelPermission", b =>
                {
                    b.Property<int>("AdminLevelId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("AdminLevelId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("AdminLevelPermissions", (string)null);
                });

            modelBuilder.Entity("CouponCategory", b =>
                {
                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("CouponId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CouponCategories", (string)null);
                });

            modelBuilder.Entity("CouponProduct", b =>
                {
                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CouponId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CouponProducts", (string)null);
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RecipientName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecipientPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Region")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Addresse__3214EC0720517029");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.AdminLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "LevelName" }, "UQ_AdminLevels_Name")
                        .IsUnique();

                    b.ToTable("AdminLevels");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.BlacklistRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminUserId")
                        .HasColumnType("int");

                    b.Property<int>("BlockedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UnblockAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Blacklis__3214EC07CC1F5DE7");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("BlockedUserId");

                    b.ToTable("BlacklistRecords");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__Brands__3214EC07EBF8F95E");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Carts__3214EC07ADAFED9C");

                    b.HasIndex(new[] { "UserId" }, "UQ_Carts_UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CartItem__3214EC073D89D384");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.HasIndex("VariantId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC07B271DEB5");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.CategoryAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowCustomInput")
                        .HasColumnType("bit");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Category__3214EC07FB7FECCB");

                    b.ToTable("CategoryAttributes");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.CategoryAttributeMapping", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryAttributeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "CategoryAttributeId")
                        .HasName("PK__Category__2B1402DCE86C9054");

                    b.HasIndex("CategoryAttributeId");

                    b.ToTable("CategoryAttributeMappings");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.CategoryAttributeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryAttributeId")
                        .HasColumnType("int");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Category__3214EC0795733785");

                    b.HasIndex("CategoryAttributeId");

                    b.ToTable("CategoryAttributeOptions");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK__ChatMess__3214EC072C0A50B3");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ApplyToAll")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("CouponType")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte>("DistributionType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExclusive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaximumDiscount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MinimumSpend")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PerUserLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UsedQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.HasIndex("StoreId");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.LoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttemptedAccount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ipaddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LoginTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__LoginHis__3214EC07A95A3CD4");

                    b.HasIndex("UserId");

                    b.ToTable("LoginHistories");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.MemberCoupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte>("UsageStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("MemberCoupons");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.MemberProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<bool?>("EmailNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsSeller")
                        .HasColumnType("bit");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("PointBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("TotalSpending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__MemberPr__3214EC07CBF77DA4");

                    b.HasIndex("LevelId");

                    b.HasIndex(new[] { "UserId" }, "UQ_MemberProfiles_UserId")
                        .IsUnique();

                    b.ToTable("MemberProfiles");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.MembershipLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("MinSpending")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Membersh__3214EC077D283FA0");

                    b.ToTable("MembershipLevels");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("PointDiscount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RecipientAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecipientPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("ShippingFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC078F47CCEE");

                    b.HasIndex("CouponId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "OrderNumber" }, "UQ_Orders_Number")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.OrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AllocatedDiscountAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CoverImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SkuCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.Property<string>("VariantName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__OrderDet__3214EC07D8EF013B");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VariantId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.OrderReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<string>("StoreReply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__OrderRev__3214EC07EDA47055");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("OrderReviews");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.PaymentLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MerchantTradeNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("RtnCode")
                        .HasColumnType("int");

                    b.Property<string>("RtnMsg")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("TradeAmt")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TradeNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__PaymentL__3214EC076A05C45F");

                    b.HasIndex("OrderId");

                    b.ToTable("PaymentLogs");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PermissionKey" }, "UQ_Permissions_Key")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.PointHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<int>("ChangeAmount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PointHis__3214EC0748BD63DC");

                    b.HasIndex("UserId");

                    b.ToTable("PointHistory", (string)null);
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ForceOffShelfBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ForceOffShelfDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ForceOffShelfReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ReApplyDate")
                        .HasColumnType("datetime");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("int");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecDefinitionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalSales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__Products__3214EC079295A641");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ForceOffShelfBy");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ProductI__3214EC0772EEB958");

                    b.HasIndex("ProductId");

                    b.HasIndex("VariantId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("SafetyStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SkuCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("VariantName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__ProductV__3214EC073A6575F7");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "SkuCode" }, "UQ_ProductVariants_SkuCode")
                        .IsUnique()
                        .HasFilter("[SkuCode] IS NOT NULL");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PromotionType")
                        .HasColumnType("int");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Promotio__3214EC07CCFDDD24");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("SellerId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.PromotionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityLimit")
                        .HasColumnType("int");

                    b.Property<int>("SoldCount")
                        .HasColumnType("int");

                    b.Property<int?>("StockLimit")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Promotio__3214EC07C9CDD985");

                    b.HasIndex("ProductId");

                    b.HasIndex("PromotionId");

                    b.ToTable("PromotionItems");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.PromotionRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int>("RuleType")
                        .HasColumnType("int");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Promotio__3214EC07269B7A44");

                    b.HasIndex("PromotionId");

                    b.ToTable("PromotionRules");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.ReturnRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdminRemark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReasonCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReasonDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("ReturnRequests");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.ReturnRequestImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("ReturnRequestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReturnRequestId");

                    b.ToTable("ReturnRequestImages");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.ReviewImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ReviewIm__3214EC074C21816B");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewImages");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07D7442CDF");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.SensitiveWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Sensitiv__3214EC079DF73360");

                    b.HasIndex("CategoryId");

                    b.ToTable("SensitiveWords");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.SensitiveWordCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Sensitiv__3214EC07156B6588");

                    b.ToTable("SensitiveWordCategories");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("StoreStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Stores__3214EC078D01D42D");

                    b.HasIndex("UserId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminReply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Subject")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__SupportT__3214EC075D10031D");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("AdminLevelId")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsBlacklisted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFirstLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Provider")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProviderId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC071CE4420D");

                    b.HasIndex("AdminLevelId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Account" }, "UQ_Users_Account")
                        .IsUnique()
                        .HasFilter("[Account] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AdminLevelPermission", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.AdminLevel", null)
                        .WithMany()
                        .HasForeignKey("AdminLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ALP_AdminLevels");

                    b.HasOne("ISpanShop.Models.EfModels.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ALP_Permissions");
                });

            modelBuilder.Entity("CouponCategory", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_CouponCategories_Categories");

                    b.HasOne("ISpanShop.Models.EfModels.Coupon", null)
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .IsRequired()
                        .HasConstraintName("FK_CouponCategories_Coupons");
                });

            modelBuilder.Entity("CouponProduct", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Coupon", null)
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .IsRequired()
                        .HasConstraintName("FK_CouponProducts_Coupons");

                    b.HasOne("ISpanShop.Models.EfModels.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_CouponProducts_Products");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Address", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Addresses_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.BlacklistRecord", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.User", "AdminUser")
                        .WithMany("BlacklistRecordAdminUsers")
                        .HasForeignKey("AdminUserId")
                        .IsRequired()
                        .HasConstraintName("FK_BlacklistRecords_AdminUser");

                    b.HasOne("ISpanShop.Models.EfModels.User", "BlockedUser")
                        .WithMany("BlacklistRecordBlockedUsers")
                        .HasForeignKey("BlockedUserId")
                        .IsRequired()
                        .HasConstraintName("FK_BlacklistRecords_BlockedUser");

                    b.Navigation("AdminUser");

                    b.Navigation("BlockedUser");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Cart", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("ISpanShop.Models.EfModels.Cart", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Carts_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.CartItem", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Carts");

                    b.HasOne("ISpanShop.Models.EfModels.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Products");

                    b.HasOne("ISpanShop.Models.EfModels.Store", "Store")
                        .WithMany("CartItems")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Stores");

                    b.HasOne("ISpanShop.Models.EfModels.ProductVariant", "Variant")
                        .WithMany("CartItems")
                        .HasForeignKey("VariantId")
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_ProductVariants");

                    b.Navigation("Cart");

                    b.Navigation("Product");

                    b.Navigation("Store");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Category", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_Categories_Parent");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.CategoryAttributeMapping", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.CategoryAttribute", "CategoryAttribute")
                        .WithMany("CategoryAttributeMappings")
                        .HasForeignKey("CategoryAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AttributeMappings_Attributes");

                    b.HasOne("ISpanShop.Models.EfModels.Category", "Category")
                        .WithMany("CategoryAttributeMappings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AttributeMappings_Categories");

                    b.Navigation("Category");

                    b.Navigation("CategoryAttribute");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.CategoryAttributeOption", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.CategoryAttribute", "CategoryAttribute")
                        .WithMany("CategoryAttributeOptions")
                        .HasForeignKey("CategoryAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AttributeOptions_Attributes");

                    b.Navigation("CategoryAttribute");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.ChatMessage", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.User", "Receiver")
                        .WithMany("ChatMessageReceivers")
                        .HasForeignKey("ReceiverId")
                        .IsRequired()
                        .HasConstraintName("FK_ChatMessages_Receiver");

                    b.HasOne("ISpanShop.Models.EfModels.User", "Sender")
                        .WithMany("ChatMessageSenders")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK_ChatMessages_Sender");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Coupon", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.User", "Seller")
                        .WithMany("Coupons")
                        .HasForeignKey("SellerId")
                        .IsRequired()
                        .HasConstraintName("FK_Coupons_Users");

                    b.HasOne("ISpanShop.Models.EfModels.Store", "Store")
                        .WithMany("Coupons")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("FK_Coupons_Stores");

                    b.Navigation("Seller");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.LoginHistory", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.User", "User")
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_LoginHistories_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.MemberCoupon", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Coupon", "Coupon")
                        .WithMany("MemberCoupons")
                        .HasForeignKey("CouponId")
                        .IsRequired()
                        .HasConstraintName("FK_MemberCoupons_Coupons");

                    b.HasOne("ISpanShop.Models.EfModels.Order", "Order")
                        .WithMany("MemberCoupons")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_MemberCoupons_Orders");

                    b.HasOne("ISpanShop.Models.EfModels.User", "User")
                        .WithMany("MemberCoupons")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_MemberCoupons_Users");

                    b.Navigation("Coupon");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.MemberProfile", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.MembershipLevel", "Level")
                        .WithMany("MemberProfiles")
                        .HasForeignKey("LevelId")
                        .IsRequired()
                        .HasConstraintName("FK_MemberProfiles_MembershipLevels");

                    b.HasOne("ISpanShop.Models.EfModels.User", "User")
                        .WithOne("MemberProfile")
                        .HasForeignKey("ISpanShop.Models.EfModels.MemberProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_MemberProfiles_Users");

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Order", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Coupon", "Coupon")
                        .WithMany("Orders")
                        .HasForeignKey("CouponId")
                        .HasConstraintName("FK_Orders_Coupons");

                    b.HasOne("ISpanShop.Models.EfModels.Store", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Stores");

                    b.HasOne("ISpanShop.Models.EfModels.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Users");

                    b.Navigation("Coupon");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.OrderDetail", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetails_Orders");

                    b.HasOne("ISpanShop.Models.EfModels.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetails_Products");

                    b.HasOne("ISpanShop.Models.EfModels.ProductVariant", "Variant")
                        .WithMany("OrderDetails")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("FK_OrderDetails_ProductVariants");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.OrderReview", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Order", "Order")
                        .WithMany("OrderReviews")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderReviews_Orders");

                    b.HasOne("ISpanShop.Models.EfModels.User", "User")
                        .WithMany("OrderReviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderReviews_Users");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.PaymentLog", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Order", "Order")
                        .WithMany("PaymentLogs")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_PaymentLogs_Orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.PointHistory", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.User", "User")
                        .WithMany("PointHistories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_PointHistory_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Product", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("FK_Products_Brands");

                    b.HasOne("ISpanShop.Models.EfModels.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_Categories");

                    b.HasOne("ISpanShop.Models.EfModels.User", "ForceOffShelfByNavigation")
                        .WithMany("Products")
                        .HasForeignKey("ForceOffShelfBy")
                        .HasConstraintName("FK_Products_Users_ForceOffShelf");

                    b.HasOne("ISpanShop.Models.EfModels.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_Stores");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("ForceOffShelfByNavigation");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.ProductImage", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductImages_Products");

                    b.HasOne("ISpanShop.Models.EfModels.ProductVariant", "Variant")
                        .WithMany("ProductImages")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("FK_ProductImages_ProductVariants");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.ProductVariant", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductVariants_Products");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Promotion", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.User", "ReviewedByNavigation")
                        .WithMany("PromotionReviewedByNavigations")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("FK_Promotions_Users_Reviewer");

                    b.HasOne("ISpanShop.Models.EfModels.User", "Seller")
                        .WithMany("PromotionSellers")
                        .HasForeignKey("SellerId")
                        .IsRequired()
                        .HasConstraintName("FK_Promotions_Users_Seller");

                    b.Navigation("ReviewedByNavigation");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.PromotionItem", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Product", "Product")
                        .WithMany("PromotionItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PromotionItems_Products");

                    b.HasOne("ISpanShop.Models.EfModels.Promotion", "Promotion")
                        .WithMany("PromotionItems")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PromotionItems_Promotions");

                    b.Navigation("Product");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.PromotionRule", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Promotion", "Promotion")
                        .WithMany("PromotionRules")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PromotionRules_Promotions");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.ReturnRequest", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Order", "Order")
                        .WithMany("ReturnRequests")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_ReturnRequests_Orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.ReturnRequestImage", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.ReturnRequest", "ReturnRequest")
                        .WithMany("ReturnRequestImages")
                        .HasForeignKey("ReturnRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ReturnRequestImages_ReturnRequests");

                    b.Navigation("ReturnRequest");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.ReviewImage", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.OrderReview", "Review")
                        .WithMany("ReviewImages")
                        .HasForeignKey("ReviewId")
                        .IsRequired()
                        .HasConstraintName("FK_ReviewImages_OrderReviews");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.SensitiveWord", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.SensitiveWordCategory", "CategoryNavigation")
                        .WithMany("SensitiveWords")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_SensitiveWords_Categories");

                    b.Navigation("CategoryNavigation");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Store", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.User", "User")
                        .WithMany("Stores")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Stores_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.SupportTicket", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.Order", "Order")
                        .WithMany("SupportTickets")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_SupportTickets_Orders");

                    b.HasOne("ISpanShop.Models.EfModels.User", "User")
                        .WithMany("SupportTickets")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_SupportTickets_Users");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.User", b =>
                {
                    b.HasOne("ISpanShop.Models.EfModels.AdminLevel", "AdminLevel")
                        .WithMany("Users")
                        .HasForeignKey("AdminLevelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Users_AdminLevels");

                    b.HasOne("ISpanShop.Models.EfModels.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("AdminLevel");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.AdminLevel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Category", b =>
                {
                    b.Navigation("CategoryAttributeMappings");

                    b.Navigation("InverseParent");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.CategoryAttribute", b =>
                {
                    b.Navigation("CategoryAttributeMappings");

                    b.Navigation("CategoryAttributeOptions");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Coupon", b =>
                {
                    b.Navigation("MemberCoupons");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.MembershipLevel", b =>
                {
                    b.Navigation("MemberProfiles");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Order", b =>
                {
                    b.Navigation("MemberCoupons");

                    b.Navigation("OrderDetails");

                    b.Navigation("OrderReviews");

                    b.Navigation("PaymentLogs");

                    b.Navigation("ReturnRequests");

                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.OrderReview", b =>
                {
                    b.Navigation("ReviewImages");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductVariants");

                    b.Navigation("PromotionItems");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.ProductVariant", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Promotion", b =>
                {
                    b.Navigation("PromotionItems");

                    b.Navigation("PromotionRules");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.ReturnRequest", b =>
                {
                    b.Navigation("ReturnRequestImages");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.SensitiveWordCategory", b =>
                {
                    b.Navigation("SensitiveWords");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.Store", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Coupons");

                    b.Navigation("Orders");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ISpanShop.Models.EfModels.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("BlacklistRecordAdminUsers");

                    b.Navigation("BlacklistRecordBlockedUsers");

                    b.Navigation("Cart");

                    b.Navigation("ChatMessageReceivers");

                    b.Navigation("ChatMessageSenders");

                    b.Navigation("Coupons");

                    b.Navigation("LoginHistories");

                    b.Navigation("MemberCoupons");

                    b.Navigation("MemberProfile");

                    b.Navigation("OrderReviews");

                    b.Navigation("Orders");

                    b.Navigation("PointHistories");

                    b.Navigation("Products");

                    b.Navigation("PromotionReviewedByNavigations");

                    b.Navigation("PromotionSellers");

                    b.Navigation("Stores");

                    b.Navigation("SupportTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
