// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.EfModels.Models;

public partial class BlacklistRecord
{
    public int Id { get; set; }

    public int BlockedUserId { get; set; }

    public int AdminUserId { get; set; }

    public string Reason { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UnblockAt { get; set; }

    public virtual User AdminUser { get; set; }

    public virtual User BlockedUser { get; set; }
}