// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.EfModels.Models;

public partial class ChatMessage
{
    public long Id { get; set; }

    public Guid SessionId { get; set; }

    public int SenderId { get; set; }

    public int ReceiverId { get; set; }

    public string Content { get; set; }

    public byte Type { get; set; }

    public bool? IsRead { get; set; }

    public DateTime? SentAt { get; set; }

    public virtual User Receiver { get; set; }

    public virtual User Sender { get; set; }
}