// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.EfModels.Models;

public partial class LoginHistory
{
    public long Id { get; set; }

    public int UserId { get; set; }

    public DateTime? LoginTime { get; set; }

    public string Ipaddress { get; set; }

    public bool? IsSuccessful { get; set; }

    public virtual User User { get; set; }
}