// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.EfModels.Models;

public partial class MembershipLevel
{
    public int Id { get; set; }

    public string LevelName { get; set; }

    public decimal MinSpending { get; set; }

    public decimal DiscountRate { get; set; }

    public virtual ICollection<MemberProfile> MemberProfiles { get; set; } = new List<MemberProfile>();
}