// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.EfModels.Models;

public partial class MemberProfile
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int LevelId { get; set; }

    public string FullName { get; set; }

    public byte? Gender { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string PhoneNumber { get; set; }

    public decimal? TotalSpending { get; set; }

    public int? PointBalance { get; set; }

    public bool? EmailNotification { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual MembershipLevel Level { get; set; }

    public virtual User User { get; set; }
}