// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.EfModels.Models;

public partial class OrderReview
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public long OrderId { get; set; }

    public byte Rating { get; set; }

    public string Comment { get; set; }

    public string SellerReply { get; set; }

    public bool? IsHidden { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<ReviewImage> ReviewImages { get; set; } = new List<ReviewImage>();

    public virtual User User { get; set; }
}