// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.MVC.Models.EfModels;

public partial class Address
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string RecipientName { get; set; }

    public string RecipientPhone { get; set; }

    public string City { get; set; }

    public string Region { get; set; }

    public string Street { get; set; }

    public bool? IsDefault { get; set; }

    public virtual User User { get; set; }
}