// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.MVC.Models.EfModels;

public partial class CartItem
{
    public int Id { get; set; }

    public int CartId { get; set; }

    public int StoreId { get; set; }

    public int ProductId { get; set; }

    public int VariantId { get; set; }

    public int Quantity { get; set; }

    public decimal? UnitPrice { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual Product Product { get; set; }

    public virtual Store Store { get; set; }

    public virtual ProductVariant Variant { get; set; }
}