// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.MVC.Models.EfModels;

public partial class OrderDetail
{
    public long Id { get; set; }

    public long OrderId { get; set; }

    public int ProductId { get; set; }

    public int? VariantId { get; set; }

    public string ProductName { get; set; }

    public string VariantName { get; set; }

    public string SkuCode { get; set; }

    public string CoverImage { get; set; }

    public decimal? Price { get; set; }

    public int Quantity { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

    public virtual ProductVariant Variant { get; set; }
}