// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.MVC.Models.EfModels;

public partial class PaymentLog
{
    public long Id { get; set; }

    public long OrderId { get; set; }

    public string MerchantTradeNo { get; set; }

    public string TradeNo { get; set; }

    public int? RtnCode { get; set; }

    public string RtnMsg { get; set; }

    public decimal? TradeAmt { get; set; }

    public string PaymentType { get; set; }

    public DateTime? PaymentDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Order Order { get; set; }
}