// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.MVC.Models.EfModels;

public partial class PointHistory
{
    public long Id { get; set; }

    public int UserId { get; set; }

    public string OrderNumber { get; set; }

    public int ChangeAmount { get; set; }

    public int BalanceAfter { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}