// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.MVC.Models.EfModels;

public partial class SensitiveWord
{
    public int Id { get; set; }

    public string Word { get; set; }

    public string Category { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedTime { get; set; }
}